---@type ppy.Extra
return {
  ext = ".conf",
  render = function(c, ansi, name)
    local lines = {
      "# vim:ft=kitty",
      "## name: " .. name,
      "## author: Dean Herbert (colour scheme), ppy.nvim (port)",
      "## Generated by :PpyExtras. Do not edit by hand.",
      "",
      "foreground " .. c.fg,
      "background " .. c.bg,
      "selection_foreground " .. c.fg,
      "selection_background " .. c.ui.selection,
      "cursor " .. c.fg,
      "cursor_text_color " .. c.bg,
      "url_color " .. c.accent,
      "",
      "active_border_color " .. c.ui.accent,
      "inactive_border_color " .. c.border,
      "bell_border_color " .. c.yellow,
      "",
      "tab_bar_background " .. c.ui.panel,
      "active_tab_foreground " .. c.fg,
      "active_tab_background " .. c.ui.panel_sel,
      "inactive_tab_foreground " .. c.muted,
      "inactive_tab_background " .. c.ui.panel,
      "",
      "mark1_foreground " .. c.bg,
      "mark1_background " .. c.blue,
      "mark2_foreground " .. c.bg,
      "mark2_background " .. c.yellow,
      "mark3_foreground " .. c.bg,
      "mark3_background " .. c.purple,
      "",
    }
    for i = 0, 15 do
      lines[#lines + 1] = ("color%d %s"):format(i, ansi[i])
    end
    return table.concat(lines, "\n") .. "\n"
  end,
}
