---@param c ppy.Colors
---@param o ppy.Config
return function(c, o)
  return {
    LazyNormal = { link = "NormalFloat" },
    LazyBackdrop = { bg = "#000000", blend = 100 },
    LazyH1 = { fg = c.bg, bg = c.accent, bold = true },
    LazyH2 = { fg = c.fg, bold = true },
    LazyButton = { fg = c.fg, bg = c.ui.list_sel },
    LazyButtonActive = { fg = c.bg, bg = c.accent, bold = true },
    LazyComment = { fg = c.muted },
    LazyCommit = { fg = c.muted },
    LazyCommitIssue = { fg = c.purple },
    LazyCommitScope = { fg = c.fg, italic = true },
    LazyCommitType = { fg = c.accent, bold = true },
    LazyDimmed = { fg = c.muted },
    LazyDir = { fg = c.fg, underline = true },
    LazyUrl = { fg = c.fg, underline = true },
    LazyProp = { fg = c.muted },
    LazyValue = { fg = c.fg },
    LazySpecial = { fg = c.accent },
    LazyReasonCmd = { fg = c.yellow },
    LazyReasonEvent = { fg = c.orange },
    LazyReasonFt = { fg = c.purple },
    LazyReasonImport = { fg = c.fg },
    LazyReasonKeys = { fg = c.cyan },
    LazyReasonPlugin = { fg = c.azure },
    LazyReasonRequire = { fg = c.blue },
    LazyReasonRuntime = { fg = c.green },
    LazyReasonSource = { fg = c.cyan },
    LazyReasonStart = { fg = c.fg },
    LazyProgressDone = { fg = c.green, bold = true },
    LazyProgressTodo = { fg = c.ui.selection },
    LazyNoCond = { fg = c.red },
    LazyLocal = { fg = c.orange },
    LazyTaskOutput = { fg = c.fg },
    LazyTaskError = { fg = c.red },
  }
end
